### ISSUE TITLE
Certification Request for jbatch v1.0.3 + jakarta batch api v1.0.2

### ISSUE THREAD

**Issue by scottkurz** [eclipse-ee4j/batch-tck#1]
- [x] Organization Name ("Organization") and, if applicable, URL\
 IBM - OpenLiberty - https://openliberty.io/

- [x] Implementation Name, Version and download URL (if applicable)\
The former reference implementation, informally known as "jbatch", Version 1.0.3, together with the Jakarta Batch API v1.0.2.   For the "jbatch" implementation, we provide Maven download links for [implementation](https://repo1.maven.org/maven2/com/ibm/jbatch/com.ibm.jbatch.container/1.0.3/com.ibm.jbatch.container-1.0.3.jar) and [SPI](https://repo1.maven.org/maven2/com/ibm/jbatch/com.ibm.jbatch.spi/1.0.3/com.ibm.jbatch.spi-1.0.3.jar) jars.  The project source repository is [here](https://github.com/WASdev/standards.jsr352.jbatch).  The Jakarta Batch API Maven coordinates are:  **jakarta.batch:jakarta.batch-api:1.0.2**.

- [x] Product Name, Version and download URL (if applicable)\
 N/A - the implementation is tested outside of a "product".

- [x] Specification Name, Version and download URL\
Jakarta Batch, V1.0, with specification document [here](https://github.com/jakartaee/specifications/blob/batch-1.0/batch/1.0/batch_1.0.pdf).

- [x] TCK Version, digital SHA-256 fingerprint and download URL\
Jakarta Batch TCK Version 1.0.2 - available for official download [here](https://download.eclipse.org/jakartabatch/tck/eftl/jakarta.batch.official.tck-1.0.2.zip), and also unofficially via Maven coordinates: **jakarta.batch:jakarta.batch.official.tck:1.0.2**:
    ```
    SHA256:  CD07AABA22BF01285176E6406268E9B822A101B79E5BD7D86170ED1A78E40427
    ```

- [x] Public URL of TCK Results Summary\
https://github.com/ee4j/batch-api/wiki/jbatch-v1.0.3-tck-v.1.0.2

- [x] Any Additional Specification Certification Requirements\
N/A

- [x] Java runtime used to run the implementation\
**Java 8**
    ```
    $ java -version 
    openjdk version "1.8.0_212"
    OpenJDK Runtime Environment (build 1.8.0_212-b04)
    OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
    ```

- [x] Summary of the information for the certification environment, operating system, cloud, ...\
    ```
   $ uname -a
  Linux skr 3.10.0-957.21.3.el7.x86_64 #1 SMP Fri Jun 14 02:54:29 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux
  
  $ cat /etc/os-release
  NAME="Red Hat Enterprise Linux Server"
  VERSION="7.6 (Maipo)"
    ```

- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).

- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by dblevins** [comment]
The TCK results should be hosted by the Compatible Implementation not by the Specification Project.  One option would be to put the results in this project somewhere:

 - https://github.com/WASdev/standards.jsr352.jbatch

Could be attached this release as an asset:

 - https://github.com/WASdev/standards.jsr352.jbatch/releases/tag/impl-1.0.3

Or even put into a wiki page or a github.io page.

**Comment by scottkurz** [comment]
Moving to spec/API project [here](https://github.com/eclipse-ee4j/batch-api/issues/5).
