### ISSUE TITLE
Convert the standalone TCK from javax -> jakarta package/property/TNS 

### ISSUE THREAD

**Issue by scottkurz** [eclipse-ee4j/batch-tck#3]
As part of EE 9 release plan: https://github.com/eclipse-ee4j/batch-api/issues/7

**Comment by thadumi** [comment]
Hi @scottkurz ,
I'd like to take care of this issue.

**Comment by scottkurz** [comment]
Hi @thadumi , thank you for volunteering.     

Let me just clarify that [this issue](https://github.com/eclipse-ee4j/jakartaee-tck/issues/162) is being used to update the batch tests within the platform TCK.    

So this issue here: https://github.com/eclipse-ee4j/batch-tck/issues/3   covers the update within this repo itself.

**Comment by scottkurz** [comment]
@thadumi, not sure how far you were planning to go here.   Since there's no compatible implementation yet (at least as far as I know), we can't test the new TCK by actually running it against a CI.     I think a simple find/replace with a code review is fine for now.   

If it turns out you are interested in taking the next step and trying to update an implementation and run the updated TCK against it, then let me know and I can try to provide pointers.

**Comment by thadumi** [comment]
> @thadumi, not sure how far you were planning to go here. Since there's no compatible implementation yet (at least as far as I know), we can't test the new TCK by actually running it against a CI. I think a simple find/replace with a code review is fine for now.

This is exactly what I started to do in a fork yesterday. 
https://github.com/thadumi/batch-tck/commit/c9b29b42d68eeb4c12cc264897079be926493737

I was planing to open a single pull request. Though, there are a lot of replaces to do therefore a lot of code to review. Should I open multiple PR instead?

Right now I was wondering about the replacement of the javaee's namespace within the xml files.
What should we do with them? Is this going to be a backlog task until the new jakarta namespace will be available? I took a look at your [issue](https://github.com/eclipse-ee4j/batch-api/issues/12)  and it seam  it's something that needs to be done.

**Comment by scottkurz** [comment]
As mentioned in https://github.com/eclipse-ee4j/batch-api/issues/12 and the ML, we will go with (the common) namespace of :
https://jakarta.ee/xml/ns/jakartaee/batch

**Comment by scottkurz** [comment]
@thadumi just wanted to note that the namespace issue has been resolved.   

If we're going to check in a mass of whitespace changes, though, I'd rather separate that out into a separate commit, and include the entire set of .java files in the project, and then have a second commit just for the non-whitespace changes.   

Going to run this by the mailing list.

**Comment by thadumi** [comment]
Hi @scottkurz ,
sorry for the delay and thanks for the updated. 
I'm going to catch up all the mails this afternoon.

**Comment by scottkurz** [comment]
Hi @thadumi .. let me also note that I just updated the master branch of the **jbatch** implementation: https://github.com/WASdev/standards.jsr352.jbatch
with a first round of the package/NS changes.  (The changes are in the **master** branch though NOT released to Maven yet).

It could be a good next step to convert the standalone TCK package/NS, and then try to follow the instructions on how to run this against the updated jbatch master branch.

I know there are quite a few instructions.. I'd expect you probably will need some help getting through them at some point so feel free to contact me.  

Thanks for your help here.

**Comment by scottkurz** [comment]
Hi @thadumi, just wanted to check in and see if you had a chance to look at this, and/or had hit any issues.    I do think all the content changes should go into 1 PR, with the commits separated into formatting vs. non-whitespace/formatting changes.   (If we do have formatting it'd be best to try to get every file in the project if feasible).

Thanks

**Comment by thadumi** [comment]
Hi @scottkurz, I has been looking into it this evening. However I didn’t make it to prepare everything for the pull request due to family issues.
I’ll try to set up everything tomorrow morning.

**Comment by scottkurz** [comment]
Thanks @thadumi.  

Didn't mean to pressure, but I know the https://github.com/WASdev/standards.jsr352.jbatch implementation isn't quite complete.   

Don't struggle too much if you're trying to run the TCK against this impl without asking for help.

**Comment by scottkurz** [comment]
Let's mark this resolved.   We have some work to do still to get the TCK actually running against **jbatch** but this massive reformatting and basic find/replace is now complete.  Thx Theodor.
