### ISSUE TITLE
Arquillian exec parent POM contains Maven properties that don't get resolved until execution time

### ISSUE THREAD

**Issue by scottkurz** [eclipse-ee4j/batch-tck#48]
This is not a good way to define the dependency in the jakarta.batch.arquillian.exec-parent artifact: 
```xml
<dependency>
   <groupId>${project.groupId}</groupId>
   <artifactId>jakarta.batch.reporting</artifactId>
   <version>${project.version}</version>
   <scope>test</scope>
</dependency>
```
because the properties don't get resolved until execution time, in the child referencing this POM as a parent. 

If we want to use a property it should be something specific to our projec.t

**Comment by OndroMih** [comment]
I've already discovered this and raise a PR to fix it: https://github.com/eclipse-ee4j/batch-tck/pull/50, including fixes and improvements for a few other things. Please review and merge if OK.
