### ISSUE TITLE
postgresql.ddl.jbatch-tck.sql: Orders table primary key is not auto-incremental

### ISSUE THREAD

**Issue by chengfang** [eclipse-ee4j/batch-tck#60]
In the ddl file for postgres, https://github.com/eclipse-ee4j/batch-tck/blob/master/com.ibm.jbatch.tck/src/main/resources/ddls/postgresql.ddl.jbatch-tck.sql#L13 , its primary key is defined as regular int:

```sql
CREATE TABLE Orders
(
    orderID  INT PRIMARY KEY,
    itemID   INT,
    quantity INT
);
```

while other ddl files all define the same column as auto-incremental column:
```sql
CREATE TABLE IF NOT EXISTS Orders
(
    orderID  INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    itemID   INT,
    quantity INT
```

Any reason for such difference?  Or should it be changed to something like `orderID  SERIAL PRIMARY KEY` to be consistent?

**Comment by scottkurz** [comment]
It looks like that should be changed. 

It looks like the INSERT    `public static final String INSERT_ORDER = "insert into app.Orders values(DEFAULT, ?, ?)"` in 
com.ibm.jbatch.tck/src/main/java/com/ibm/jbatch/tck/artifacts/chunkartifacts/ConnectionHelper.java depends on this.
