### ISSUE TITLE
pom files contain RI-specific description

### ISSUE THREAD

**Issue by chengfang** [eclipse-ee4j/batch-tck#61]
se-classpath/pom and sigtest/pom.xml contain the following jbatch-specific info:

com.ibm.jbatch.tck.exec/pom.xml:    
<name>Jakarta Batch TCK Execution (using JBatch, the former RI, against TCK Maven module)</name>

com.ibm.jbatch.tck.sigtest.exec/pom.xml:    
<name>Jakarta Batch Signature Test Execution (using JBatch, the former RI, against TCK maven module)</name>

When running the TCK with other impls like jberet, we still see the above in the test output, unless we go out of the way to change it in pom.xml files as part of the TCK configuration. I suggest using some generic description to users don't have to change it.

**Comment by OndroMih** [comment]
Hi, @chengfang , 

As these example projects are configured for JBatch implementation, the name of the project explicitly mentions JBatch. . The `com.ibm.jbatch.tck.exec` and `com.ibm.jbatch.tck.sigtest.exec` are example projects, which you can modify before running the TCK. You are free to modify the name of the maven module in your local version before running the TCK if you're adapting it for another implementation. I also suggest that you change the module's group name and artifact name. 

The Batch TCK guide mentions this in section 8:

> We attempt to
describe below the essential aspects of the configuration necessary to execute the TCK and claim
compliance vs. the parts that may be modified, taking the runner POM only as a sample starting
point.

Sections 9 (about Java SE) and 11 (about signature tests) then specify what is required to have in the pom.xml of the runner project. So you can take the example projects and modify anything in their pom.xml except the required parts that need to stay there.

I personally think that each implementation should create its own copies of the example projects and keep them in version control. And in that case it's better to change the name, group ID, artifact ID and any other metadata of the maven module to match the implementation it runs the TCK against. There's not much value in changing the name of the example project. But if you think it would really help you or others, feel free to raise a PR with a better name for the maven modules.

**Comment by scottkurz** [comment]
So we're overloading the usage of the parts as we build the runner from them:
```xml
        <file>
            <source>../com.ibm.jbatch.tck.exec/pom.xml</source>
            <outputDirectory>/runners/se-classpath</outputDirectory>
        </file>
        <file>
            <source>../com.ibm.jbatch.tck.sigtest.exec/pom.xml</source>
            <outputDirectory>/runners/sigtest</outputDirectory>
        </file>
```

Maybe ideally we'd have build logic to leave the "JBatch" name in the source location but substitute with your description as the assembly gets built.    But it doesn't seem worth setting up a "filter" .  @chengfang if you think #64 is better I'm OK merging it then.... it still makes sense in the original context of the `com.ibm.jbatch.tck.exec/pom.xml`, etc. locations.

**Comment by scottkurz** [comment]
Seems like enough time to wait.  Merging.
