### ISSUE TITLE
Updating the copyright to 2012-2020

### ISSUE THREAD

**Issue by thadumi** [eclipse-ee4j/batch-tck#9]
As discussed in https://github.com/eclipse-ee4j/batch-tck/pull/8#discussion_r407011409
We need to update the copyright in something like `Copyright 2012, 2020 International Business Machines Corp. and others `

**Comment by thadumi** [comment]
@scottkurz can you assign it to me?
I'm going to open the PR as soon as we close #8

**Comment by scottkurz** [comment]
Fixed by #10
